export const FIELD_NAMES = {
  ARP_NO: "ArpNo",
  PROPERTY_ID: "PID",
  FIRST_NAME: "fname",
  MIDDLE_NAME: "mname",
  LAST_NAME: "lname",
  ADDRESS: "Address",
  TIN: "TIN",
  TELEPHONE: "Telephone",

  ADMIN_FIRST_NAME: "AdminFname",
  ADMIN_MIDDLE_NAME: "AdminMname",
  ADMIN_LAST_NAME: "AdminLname",
  ADMIN_ADDRESS: "AdminAddress",
  ADMIN_TIN: "AdminTIN",
  ADMIN_TELEPHONE: "AdminTel",

  NO_AND_STREET: "noAndSt",
  BARANGAY: "Brgy",
  OCT: "oct",
  SURVEY: "Survey",
  CCT: "cct",
  LOT: "LOT",
  DATE: "DATE",
  BLOCK: "BLOCK",

  TAXABILITY: "TAXABILITY",
  QUARTER: "qtr",
  YEAR: "year",
  EFFECTIVITY_DATE: "dateOfEffectivity",
  BOUNDARIES: "Boundaries",
  CLASSIFICATION: "classification",

  OLD_ARP: "oldArp",
  MEMORANDA: "memoranda",
  PREVIOUS_OWNER: "previousOwner",
  PREVIOUS_AV: "previousAV",
  PREVIOUS_PID: "previousPid",
};
