export const BRGY_LIST = [
  "I-A",
  "I-B",
  "I-C",
  "II-A",
  "II-B",
  "II-C",
  "II-D",
  "II-E",
  "II-F",
  "III-A",
  "III-B",
  "III-C",
  "III-D",
  "III-E",
  "III-F",
  "IV-A",
  "IV-B",
  "IV-C",
  "V-A",
  "V-B",
  "V-C",
  "V-D",
  "VI-A",
  "VI-B",
  "VI-C",
  "VI-D",
  "VI-E",
  "VII-A",
  "VII-B",
  "VII-C",
  "VII-D",
  "VII-E",
  "STA. ANA",
  "STO. ANGEL (Ilog)",
  "SAN ANTONIO I (Balanga)",
  "SAN ANTONIO II (Sapa)",
  "SAN BARTOLOME",
  "BAUTISTA",
  "SAN BUENAVENTURA (Palakpakin)",
  "STA. CATALINA (Sandig)",
  "CONCEPCION",
  "SAN CRISPIN",
  "STO. CRISTO",
  "SAN CRISTOBAL",
  "STA. CRUZ (Putol)",
  "DEL REMEDIO (Wawa)",
  "SAN DIEGO",
  "DOLORES",
  "STA. ELENA",
  "STA. FILOMENA (Banlagin)",
  "SAN FRANCISCO (Calihan)",
  "SAN GABRIEL",
  "SAN GREGORIO",
  "STA. ISABEL",
  "SAN IGNACIO",
  "SAN ISIDRO (Balagbag)",
  "SAN JOAQUIN",
  "SAN JOSE (Malamig)",
  "SAN JUAN",
  "SAN LORENZO (Saluyan)",
  "SAN LUCAS I (Malinaw)",
  "SAN LUCAS II (Malinaw)",
  "SAN MARCOS (Tikew)",
  "STA. MARIA",
  "STA. MA. MAGDALENA",
  "SAN MATEO",
  "SAN MIGUEL",
  "STA. MONICA",
  "SAN NICOLAS",
  "STO. NIÑO",
  "SAN PEDRO",
  "SAN RAFAEL",
  "SAN ROQUE",
  "STMO. ROSARIO",
  "SANTIAGO I (Bulaho)",
  "SANTIAGO II (Bulaho)",
  "SOLEDAD",
  "STA. VERONICA (Bae)",
  "SAN VICENTE",
];
