export const BRGY_CODE = {
    "I-A": "001",
    "I-B": "002",
    "I-C": "003",
    "II-A": "004",
    "II-B": "005",
    "II-C": "006",
    "II-D": "007",
    "II-E": "008",
    "II-F": "009",
    "III-A": "010",
    "III-B": "011",
    "III-C": "012",
    "III-D": "013",
    "III-E": "014",
    "III-F": "015",
    "IV-A": "016",
    "IV-B": "017",
    "IV-C": "018",
    "V-A": "019",
    "V-B": "020",
    "V-C": "021",
    "V-D": "022",
    "VI-A": "023",
    "VI-B": "024",
    "VI-C": "025",
    "VI-D": "026",
    "VI-E": "027",
    "VII-A": "028",
    "VII-B": "029",
    "VII-C": "030",
    "VII-D": "031",
    "VII-E": "032",
    "STA. ANA": "033",
    "STO. ANGEL (Ilog)": "034",
    "SAN ANTONIO I (Balanga)": "035",
    "SAN ANTONIO II (Sapa)": "036",
    "SAN BARTOLOME": "037",
    "BAUTISTA": "038",
    "SAN BUENAVENTURA (Palakpakin)": "039",
    "STA. CATALINA (Sandig)": "040",
    "CONCEPCION": "041",
    "SAN CRISPIN": "042",
    "STO. CRISTO": "043",
    "SAN CRISTOBAL": "044",
    "STA. CRUZ  (Putol)": "045",
    "DEL REMEDIO (Wawa)": "046",
    "SAN DIEGO": "047",
    "DOLORES": "048",
    "STA. ELENA": "049",
    "STA. FILOMENA (Banlagin)": "050",
    "SAN FRANCISCO (Calihan)": "051",
    "SAN GABRIEL": "052",
    "SAN GREGORIO": "053",
    "STA. ISABEL": "054",
    "SAN IGNACIO": "055",
    "SAN ISIDRO (Balagbag)": "056",
    "SAN JOAQUIN": "057",
    "SAN JOSE (Malamig)": "058",
    "SAN JUAN": "059",
    "SAN LORENZO (Saluyan)": "060",
    "SAN LUCAS I (Malinaw)": "061",
    "SAN LUCAS II (Malinaw)": "062",
    "SAN MARCOS (Tikew)": "063",
    "STA. MARIA": "064",
    "STA. MA. MAGDALENA": "065",
    "SAN MATEO": "066",
    "SAN MIGUEL": "067",
    "STA. MONICA": "068",
    "SAN NICOLAS": "069",
    "STO. NIÑO": "070",
    "SAN PEDRO": "071",
    "SAN RAFAEL": "072",
    "SAN ROQUE": "073",
    "STMO. ROSARIO": "074",
    "SANTIAGO I (Bulaho)": "075",
    "SANTIAGO II (Bulaho)": "076",
    "SOLEDAD": "077",
    "STA. VERONICA (Bae)": "078",
    "SAN VICENTE": "079",
};

export const BRGY_DISTRICTS = {
    "I-A": "01",
    "I-B": "01",
    "I-C": "01",
    "II-A": "01",
    "II-B": "01",
    "II-C": "01",
    "II-D": "01",
    "II-E": "01",
    "II-F": "01",
    "III-A": "01",
    "III-B": "01",
    "III-C": "01",
    "III-D": "01",
    "III-E": "01",
    "III-F": "01",
    "IV-A": "01",
    "IV-B": "01",
    "IV-C": "01",
    "V-A": "01",
    "V-B": "01",
    "V-C": "01",
    "V-D": "01",
    "VI-A": "01",
    "VI-B": "01",
    "VI-C": "01",
    "VI-D": "01",
    "VI-E": "01",
    "VII-A": "01",
    "VII-B": "01",
    "VII-C": "01",
    "VII-D": "01",
    "VII-E": "01",
    "STA. ANA": "07",
    "STO. ANGEL (Ilog)": "02",
    "SAN ANTONIO I (Balanga)": "07",
    "SAN ANTONIO II (Sapa)": "07",
    "SAN BARTOLOME": "04",
    "BAUTISTA": "04",
    "SAN BUENAVENTURA (Palakpakin)": "02",
    "STA. CATALINA (Sandig)": "02",
    "CONCEPCION": "02",
    "SAN CRISPIN": "05",
    "STO. CRISTO": "07",
    "SAN CRISTOBAL": "03",
    "STA. CRUZ  (Putol)": "07",
    "DEL REMEDIO (Wawa)": "05",
    "SAN DIEGO": "02",
    "DOLORES": "02",
    "STA. ELENA": "03",
    "STA. FILOMENA (Banlagin)": "05",
    "SAN FRANCISCO (Calihan)": "07",
    "SAN GABRIEL": "06",
    "SAN GREGORIO": "07",
    "STA. ISABEL": "02",
    "SAN IGNACIO": "07",
    "SAN ISIDRO (Balagbag)": "07",
    "SAN JOAQUIN": "07",
    "SAN JOSE (Malamig)": "07",
    "SAN JUAN": "05",
    "SAN LORENZO (Saluyan)": "02",
    "SAN LUCAS I (Malinaw)": "05",
    "SAN LUCAS II (Malinaw)": "05",
    "SAN MARCOS (Tikew)": "05",
    "STA. MARIA": "06",
    "STA. MA. MAGDALENA": "05",
    "SAN MATEO": "05",
    "SAN MIGUEL": "06",
    "STA. MONICA": "04",
    "SAN NICOLAS": "05",
    "STO. NIÑO": "03",
    "SAN PEDRO": "02",
    "SAN RAFAEL": "05",
    "SAN ROQUE": "04",
    "STMO. ROSARIO": "06",
    "SANTIAGO I (Bulaho)": "04",
    "SANTIAGO II (Bulaho)": "04",
    "SOLEDAD": "06",
    "STA. VERONICA (Bae)": "04",
    "SAN VICENTE": "07",
};