export const BRGY_OPTIONS = [
  { label: "I-A", value: "I-A" },
  { label: "I-B", value: "I-B" },
  { label: "I-C", value: "I-C" },
  { label: "II-A", value: "II-A" },
  { label: "II-B", value: "II-B" },
  { label: "II-C", value: "II-C" },
  { label: "II-D", value: "II-D" },
  { label: "II-E", value: "II-E" },
  { label: "II-F", value: "II-F" },
  { label: "III-A", value: "III-A" },
  { label: "III-B", value: "III-B" },
  { label: "III-C", value: "III-C" },
  { label: "III-D", value: "III-D" },
  { label: "III-E", value: "III-E" },
  { label: "III-F", value: "III-F" },
  { label: "IV-A", value: "IV-A" },
  { label: "IV-B", value: "IV-B" },
  { label: "IV-C", value: "IV-C" },
  { label: "V-A", value: "V-A" },
  { label: "V-B", value: "V-B" },
  { label: "V-C", value: "V-C" },
  { label: "V-D", value: "V-D" },
  { label: "VI-A", value: "VI-A" },
  { label: "VI-B", value: "VI-B" },
  { label: "VI-C", value: "VI-C" },
  { label: "VI-D", value: "VI-D" },
  { label: "VI-E", value: "VI-E" },
  { label: "VII-A", value: "VII-A" },
  { label: "VII-B", value: "VII-B" },
  { label: "VII-C", value: "VII-C" },
  { label: "VII-D", value: "VII-D" },
  { label: "VII-E", value: "VII-E" },
  { label: "STA. ANA", value: "STA. ANA" },
  { label: "STO. ANGEL (Ilog)", value: "STO. ANGEL (Ilog)" },
  { label: "SAN ANTONIO I (Balanga)", value: "SAN ANTONIO I (Balanga)" },
  { label: "SAN ANTONIO II (Sapa)", value: "SAN ANTONIO II (Sapa)" },
  { label: "SAN BARTOLOME", value: "SAN BARTOLOME" },
  { label: "BAUTISTA", value: "BAUTISTA" },
  { label: "SAN BUENAVENTURA (Palakpakin)", value: "SAN BUENAVENTURA (Palakpakin)" },
  { label: "STA. CATALINA (Sandig)", value: "STA. CATALINA (Sandig)" },
  { label: "CONCEPCION", value: "CONCEPCION" },
  { label: "SAN CRISPIN", value: "SAN CRISPIN" },
  { label: "STO. CRISTO", value: "STO. CRISTO" },
  { label: "SAN CRISTOBAL", value: "SAN CRISTOBAL" },
  { label: "STA. CRUZ  (Putol)", value: "STA. CRUZ  (Putol)" },
  { label: "DEL REMEDIO (Wawa)", value: "DEL REMEDIO (Wawa)" },
  { label: "SAN DIEGO", value: "SAN DIEGO" },
  { label: "DOLORES", value: "DOLORES" },
  { label: "STA. ELENA", value: "STA. ELENA" },
  { label: "STA. FILOMENA (Banlagin)", value: "STA. FILOMENA (Banlagin)" },
  { label: "SAN FRANCISCO (Calihan)", value: "SAN FRANCISCO (Calihan)" },
  { label: "SAN GABRIEL", value: "SAN GABRIEL" },
  { label: "SAN GREGORIO", value: "SAN GREGORIO" },
  { label: "STA. ISABEL", value: "STA. ISABEL" },
  { label: "SAN IGNACIO", value: "SAN IGNACIO" },
  { label: "SAN ISIDRO (Balagbag)", value: "SAN ISIDRO (Balagbag)" },
  { label: "SAN JOAQUIN", value: "SAN JOAQUIN" },
  { label: "SAN JOSE (Malamig)", value: "SAN JOSE (Malamig)" },
  { label: "SAN JUAN", value: "SAN JUAN" },
  { label: "SAN LORENZO (Saluyan)", value: "SAN LORENZO (Saluyan)" },
  { label: "SAN LUCAS I (Malinaw)", value: "SAN LUCAS I (Malinaw)" },
  { label: "SAN LUCAS II (Malinaw)", value: "SAN LUCAS II (Malinaw)" },
  { label: "SAN MARCOS (Tikew)", value: "SAN MARCOS (Tikew)" },
  { label: "STA. MARIA", value: "STA. MARIA" },
  { label: "STA. MA. MAGDALENA", value: "STA. MA. MAGDALENA" },
  { label: "SAN MATEO", value: "SAN MATEO" },
  { label: "SAN MIGUEL", value: "SAN MIGUEL" },
  { label: "STA. MONICA", value: "STA. MONICA" },
  { label: "SAN NICOLAS", value: "SAN NICOLAS" },
  { label: "STO. NIÑO", value: "STO. NIÑO" },
  { label: "SAN PEDRO", value: "SAN PEDRO" },
  { label: "SAN RAFAEL", value: "SAN RAFAEL" },
  { label: "SAN ROQUE", value: "SAN ROQUE" },
  { label: "STMO. ROSARIO", value: "STMO. ROSARIO" },
  { label: "SANTIAGO I (Bulaho)", value: "SANTIAGO I (Bulaho)" },
  { label: "SANTIAGO II (Bulaho)", value: "SANTIAGO II (Bulaho)" },
  { label: "SOLEDAD", value: "SOLEDAD" },
  { label: "STA. VERONICA (Bae)", value: "STA. VERONICA (Bae)" },
  { label: "SAN VICENTE", value: "SAN VICENTE" },
];
